name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make -j
    - name: make check
      run: cd build && make check -j
    - name: make distcheck
      run: cd build && make distcheck -j
    - name: Run Benchmarks
      run: |
        python3 -m venv venv
        source venv/bin/activate
        python3 run_benchmarks.py --executable build/bench-matmul
